config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  registrations: 'users/registrations'
  }
  resources :authors
  resources :posts
  resources :comments
  resources :users

  root to: "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :posts
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, uniqueness: true

  before_create :add_record
  before_destroy :delete_record
  before_destroy :delete_posts

  accepts_nested_attributes_for :posts

  def add_record
    ActivityLog.create(description:"Author with email-id #{self.email} is added",operation: :createAuthor)
  end
 
  def delete_record
    ActivityLog.create(description:"Author with email-id #{self.email} is destroyed",operation: :destroyAuthor)
  end

  def delete_posts
    post_ids = posts.pluck(:id)
    #this deletes only the join table entry
    posts.destroy_all
    Post.where(id: post_ids).destroy_all
  end  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
    @author.posts.build(title: "First post")
    @author.posts.build(title: "Second post")
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to authors_path, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to authors_path, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:firstname, :lastname, :email, :City, :State, posts_attributes: [:id, :title, :post_content ])
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
<% if author.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

  <ul>
    <% author.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="center-align-form">
  <div class="field form-group row ">
    <%= form.label :firstname, :class=> "col-lg-3 col-form-label col-form-label-lg" %>
    <div class="col-lg-4 col-md-10 input-text-border">
      <%= form.text_field :firstname, :class => "form-control" %>
    </div>
  </div>

  <div class="field form-group row ">
    <%= form.label :lastname, :class=> "col-lg-3 col-form-label col-form-label-lg" %>
    <div class="col-lg-4 col-md-10 input-text-border">
      <%= form.text_field :lastname, :class => "form-control" %>
    </div>
  </div>

  <div class="field form-group row ">
    <%= form.label :email, :class=> "col-lg-3 col-form-label col-form-label-lg" %>
    <div class="col-lg-4 col-md-10 input-text-border">
      <%= form.text_field :email, :class => "form-control" %>
    </div>
  </div>

  <div class="field form-group row ">
    <%= form.label :City, :class=> "col-lg-3 col-form-label col-form-label-lg" %>
    <div class="col-lg-4 col-md-10 input-text-border">
      <%= form.text_field :City,:class => "form-control" %>
    </div>
  </div>

  <div class="field form-group row ">
    <%= form.label :State, :class=> "col-lg-3 col-form-label col-form-label-lg"%>
    <div class="col-lg-4 col-md-10 input-text-border">
      <%= form.text_field :State, :class => "form-control" %>
    </div>
  </div>
  <hr>
  <h3 class="text-center"> Posts</h3>
  <%= form.fields_for :posts do |p|%>

  <div class="field form-group row ">
    <%= p.label :title, :class=> "col-lg-3 col-form-label col-form-label-lg" %>
    <div class="col-lg-4 col-md-10 input-text-border">
      <%= p.text_field :title,:class => "form-control" %>
    </div>
  </div>

  <div class="field form-group row ">
    <%= p.label :post_content, :class=> "col-lg-3 col-form-label col-form-label-lg" %>
    <div class="col-lg-4 col-md-10 input-text-border">
      <%= p.text_field :post_content,:class => "form-control" %>
    </div>
  </div>

  <% end %>

  <div class="center-align-form">
    <div class="actions">
      <%= form.submit class: "btn btn-primary text-white" %>
    </div>
  </div>

</div>
<% end %>

app/views/authors/edit.html.erb
<h1 class="text-center">Editing Author</h1>

<%= render 'form', author: @author %>

app/views/authors/index.html.erb
<div class="text-center">
  <h1>Authors</h1>
  <div class="center-align">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Firstname</th>
          <th>Lastname</th>
          <th>Email</th>
          <th>City</th>
          <th>State</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @authors.each do |author| %>
        <tr>
          <td class="author_name"><%= author.firstname %></td>
          <td><%= author.lastname %></td>
          <td><%= author.email %></td>
          <td><%= author.City %></td>
          <td><%= author.State %></td>
          <td><%= link_to ' ', author, class:"fa fa-address-book btn btn-info"%></td>
          <td><%= link_to ' ', edit_author_path(author), class:"fa fa-edit btn btn-primary" %></td>
          <td><%= link_to ' ', author, method: :delete, data: { confirm: 'Are you sure?' }, class:"fa fa-trash-o btn btn-danger" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>
<div class="text-center">
<%= link_to 'New Author', new_author_path, class:"btn btn-primary text-white" %>
</div>

app/views/authors/new.html.erb
<h1 class="text-center">New Author</h1>
<%= render 'form', author: @author %>

app/views/authors/show.html.erb
<p>
  <strong>Firstname:</strong>
  <%= @author.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @author.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>City:</strong>
  <%= @author.City %>
</p>

<p>
  <strong>State:</strong>
  <%= @author.State %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>