config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  registrations: 'users/registrations'
  }
  resources :authors
  resources :posts
  resources :comments
  resources :users

  root to: "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= users_path %>">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">
      <li class="nav-item ">
        <a class="nav-link" href="<%= posts_path %>">Posts <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="<%= authors_path %>">Authors</a>
      </li>
      <li class="nav-item log-out-list-item">
        <%= link_to '', destroy_user_session_path, method: :delete, class:"nav-link fa fa-sign-out " %>
      </li>
      <% end %>

    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render "/layouts/navbar" %>
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
  <%= yield %>

</body>

</html>